### PR TITLE
F/message metrics

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

This will create a new message consumer which can report metrics on message internals such as `message_version`

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Add a new handler table as well as a way to specify which "mode" the consumer should be in.  If we need to create a new consumer this should be extensible.

If investigator gets to large to maintain, converting this to multiple components should be pretty straight forward.

### CODE REVIEW

**Comment by goern** [comment]
is this ok to be merged?

**Comment by KPostOffice** [comment]
@goern Yeah

**Review by pacospace — APPROVED** [review]
lgtm! 👍🏼

**Pull request merged**
