### PR TITLE
Move to thoth namespace

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: #343 

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by harshad16** [comment]
@fridex this needs rebase.

**Comment by fridex** [comment]
rebased, PTAL

**Review by harshad16 — APPROVED** [review]
lgtm,
thanks for the udpate :)

**Review by KPostOffice — APPROVED** [review]

**Review by pacospace — APPROVED** [review]
:100: Thanks! :beers:

**Pull request merged**
