### PR TITLE
use v1 handler to avert exceptions

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

investigator is failing in test due to missing handlers

### CODE REVIEW

**Comment by pacospace** [comment]
> ## Related Issues and Dependencies
> investigator is failing in stage due to missing handlers

What is the procedure in general?

I expect that as thoth maintainer:

- [ ] Update thoth-messaging message and version
- [ ] Update investigator when I want to get that in.

Do we expect investigator to fail? Or do we expect investigator to send warnings about messages received that cannot be handled?

Can we write a procedure in docs on what to do?

@KPostOffice @fridex @harshad16 @goern

**Comment by KPostOffice** [comment]
I can open a PR which unsubscribes from the topic and logs a WARNING. Wdyt @pacospace?

**Comment by pacospace** [comment]
> I can open a PR which unsubscribes from the topic and logs a WARNING. Wdyt @pacospace?

I like it, thanks @KPostOffice , can we send also specific metric giving us a warning with labels message name, message_version not handled?

**Comment by KPostOffice** [comment]
@pacospace See #465

**Comment by pacospace** [comment]
> @pacospace See #465

With 465 merged, do we need this PR @KPostOffice ?

**Comment by KPostOffice** [comment]
I don't think so. We still need to add handlers for those two message versions but this is just a work-around that we don't need anymore.

**Pull request closed without merging**
