### PR TITLE
constrain thoth-messaging

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

https://github.com/thoth-station/messaging/pull/373

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
👍🏼

**Comment by goern** [comment]
`<=` ? how will this work with future releases?

**Comment by KPostOffice** [comment]
@goern With pydantic, calling conventions will change so I constrained the message version.  Changes need to be made to the modules and components to use future versions.

**Pull request merged**
