### PR TITLE
Do not pass arguments that are prepared in adviser container

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Fixes: #902
Depends-On: thoth-station/common#1109
Related: thoth-station/adviser#1670
Related: thoth-station/management-api#705

## This introduces a breaking change

- [x] Yes

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm

**Review by pacospace — COMMENTED** [review]
do we need an update in https://github.com/thoth-station/investigator/blob/b51e4acacc2f2e2bda80a65527853ac1328a7e3d/thoth/investigator/adviser_re_run/investigate_adviser_re_run.py#L52 as well?

**Review by pacospace — APPROVED** [review]
Thanks 💯

**Comment by fridex** [comment]
With https://github.com/thoth-station/investigator/pull/457 this can go in.

**Pull request merged**
