### PR TITLE
mark missing packages and schedule keb admin

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

Fixes: #362

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm
thanks :100:

**Comment by goern** [comment]
what needs to be done to get this merged?

**Comment by KPostOffice** [comment]
@fridex Needs to take a look at it I think. It needs the approved label

**Review by fridex — APPROVED** [review]
lgtm, thanks! 👍🏻

**Pull request merged**
