### PR TITLE
break handler tablers based on namespace

### PR DESCRIPTION
**Pull request by KPostOffice**
bottleneck due to argo workflow limit which kept user workflows in backend from getting scheduled due to middletier workflow limit

Signed-off-by: Kevin <kpostlet@redhat.com>

## Related Issues and Dependencies

fixes: #673 

## This introduces a breaking change

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by KPostOffice** [comment]
This is ready for review

**Review by harshad16 — COMMENTED** [review]
lgtm
really like the solution of having multiple investigator consumers based on the type of message (in this case namespace)

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

Thanks for the work :+1:

**Pull request merged**
