### PR TITLE
Manual dependency update

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Direct dependency had to be adjusted, otherwise Pipenv was unable to lock the stack.

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
Will merge this to continue with https://github.com/thoth-station/investigator/pull/445 and test it in test environment/

**Comment by harshad16** [comment]
was it beacuse of this https://github.com/thoth-station/common/blob/b93627edfb51e1816995c24e1528366c678e04d8/requirements.txt#L10

**Comment by fridex** [comment]
> was it beacuse of this https://github.com/thoth-station/common/blob/b93627edfb51e1816995c24e1528366c678e04d8/requirements.txt#L10

It looks to me Pipenv did not consider an older release of openshift which has a valid resolution:

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches kubernetes>=11.0.0,~=11.0.0,~=12.0 (from thoth-common==0.24.1->-r /tmp/pipenv9okj6_mbrequirements/pipenv-sqh6hhc2-constraints.txt (line 6))
Tried: 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 2.0.0, 2.0.0, 3.0.0, 3.0.0, 4.0.0, 4.0.0, 5.0.0, 5.0.0, 6.0.0, 6.0.0, 6.1.0, 6.1.0, 7.0.0, 7.0.0, 7.0.1, 7.0.1, 8.0.0, 8.0.0, 8.0.1, 8.0.1, 8.0.2, 8.0.2, 9.0.0, 9.0.0, 9.0.1, 9.0.1, 10.0.0, 10.0.0, 10.0.1, 10.0.1, 10.1.0, 10.1.0, 11.0.0, 11.0.0, 12.0.0, 12.0.0, 12.0.1, 12.0.1
Skipped pre-versions: 0.0.0a2, 0.0.0a2, 0.0.0a5, 0.0.0a5, 1.0.0a2, 1.0.0a2, 1.0.0a3, 1.0.0a4, 1.0.0a4, 1.0.0a5, 1.0.0a5, 1.0.0b1, 1.0.0b1, 1.0.0b2, 1.0.0b2, 1.0.0b3, 1.0.0b3, 2.0.0a1, 2.0.0a1, 2.0.0b1, 2.0.0b1, 3.0.0a1, 3.0.0a1, 3.0.0b1, 3.0.0b1, 4.0.0a1, 4.0.0a1, 4.0.0b1, 4.0.0b1, 5.0.0b1, 5.0.0b1, 6.0.0b1, 6.0.0b1, 7.0.0a1, 7.0.0a1, 7.0.0b1, 7.0.0b1, 8.0.0a1, 8.0.0a1, 8.0.0b1, 8.0.0b1, 9.0.0a1, 9.0.0a1, 9.0.0b1, 9.0.0b1, 10.0.0a1, 10.0.0a1, 11.0.0a1, 11.0.0a1, 11.0.0b1, 11.0.0b1, 11.0.0b2, 11.0.0b2, 12.0.0a1, 12.0.0a1, 12.0.0b1, 12.0.0b1, 17.14.0a1, 17.14.0a1
There are incompatible versions in the resolved dependencies:
  kubernetes>=11.0.0 (from argo-workflows==3.6.1->thoth-common==0.24.1->-r /tmp/pipenv9okj6_mbrequirements/pipenv-sqh6hhc2-constraints.txt (line 6))
  kubernetes~=11.0.0 (from thoth-common==0.24.1->-r /tmp/pipenv9okj6_mbrequirements/pipenv-sqh6hhc2-constraints.txt (line 6))
  kubernetes~=12.0 (from openshift==0.12.0->thoth-common==0.24.1->-r /tmp/pipenv9okj6_mbrequirements/pipenv-sqh6hhc2-constraints.txt (line 6))
```

But openshift==0.11.2 is a valid resolution, pipenv tried only 0.12.0.

**Comment by fridex** [comment]
@harshad16 PTAL if this can go in

**Comment by harshad16** [comment]
lgtm, let get this manually in
there seems to be request going on ci .

**Comment by fridex** [comment]
> lgtm, let get this manually in
> there seems to be request going on ci .

Thanks! :+1:

**Pull request merged**
